### PR TITLE
Expand source_* params

### PR DESCRIPTION
**Pull request by kimor79**
This allows one to do, e.g.: source_category => "%{[@metadata][source_category]}"

### CODE REVIEW

**Comment by bin3377** [comment]
There is a logic problem for this change. If multiple events sent with single HTTP request, only the value of the very last event will be evaluated and sending through headers. 

So it only works in 2 scenarios:
1. sending every event in a single request
2. the fields used in headers are consistent in all events

I think we need a document for clarify the cases

**Comment by kimor79** [comment]
How/when does it send multiple events in a single request?

**Comment by bin3377** [comment]
when setting `@interval` > 0, the messages in a period of time will be accumulated and sent together

**Comment by kimor79** [comment]
Is there a way to set the source category within the event itself?

**Comment by bin3377** [comment]
there is not such way since the payload is actually considered as a plain text.
A possible alternative way is using `@format` to send tag(s) as prefix of each line and then parsing them back when query from sumo web UI. For example:
```
@format = "%{@timestamp} [tag1=%{tag1}] [tag2=%{tag2}]%{message}
```
will produce log line looks like: 
```
2018-04-18 13:21:32 [tag1=AAA] [tag2=BBB]The real message
```
and then you can use something as:
```
<query>
| parse "[tag1=*]" as tag1
| parse "[tag2=*]" as tag2
```

**Pull request closed without merging**
